repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^cot-go-transformer/(gogpt|scripts|tests)/
      - id: ruff-format
        files: ^cot-go-transformer/(gogpt|scripts|tests)/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        files: ^cot-go-transformer/
      - id: end-of-file-fixer
        files: ^cot-go-transformer/
      - id: check-yaml
        files: ^cot-go-transformer/
      - id: check-added-large-files
        args: [--maxkb=1024]
